### PR TITLE
Some Time Functions

### PR DESCRIPTION
**Pull request by mcarmonaa**
Month function is necessary to run the testing queries.

### CODE REVIEW

**Comment by erizocosmico** [comment]
Lgtm. (Can’t review with the UI via mobile).

 Might it be worth it to have a generic function that receives a func(time.Time) int to extract date components?
Then NewGetDatePart(time.Time.Year), NewGetDatePart(time.Time.Month) and so on to use it (I think this is the first time I come up with an use case for method expressions).

Since we’re gonna have three functions that are exactly equal except for the method call this might be worth considering.

On Fri, 2 Mar 2018 at 09:21, Manuel Carmona <notifications@github.com<mailto:notifications@github.com>> wrote:

@mcarmonaa<https://github.com/mcarmonaa> requested your review on: src-d/go-mysql-server#79<https://github.com/src-d/go-mysql-server/pull/79> MONTH function.

**Comment by mcarmonaa** [comment]
Because of @erizocosmico proposal, I refactored the code for year and  month functions and added those functions with the same pattern, so now we have:
**YEAR, MONTH, DAY, HOUR, MINUTE, SECOND, DAYOFYEAR**

**Comment by ajnavarro** [comment]
@mcarmonaa Rebase and merge please

**Comment by ajnavarro** [comment]
rebase and merge please

**Pull request merged**
