### PR TITLE
 sql: resolve tables with database qualifier

### LINKED ISSUE #402: Resolve tables with database qualifier
Right now, tables can't have database qualifiers. We should be able to resolve them with database qualifiers.

We should check if columns can also be qualified with the database. If they can, they should also be handled.

See: https://github.com/src-d/gitbase/issues/361#issuecomment-427285397

### PR DESCRIPTION
**Pull request by erizocosmico**
Depends on #411 

Closes #402

### CODE REVIEW

**Comment by erizocosmico** [comment]
Rebased

**Comment by ajnavarro** [comment]
@erizocosmico the last rebase please!

**Comment by erizocosmico** [comment]
Rebased

**Comment by erizocosmico** [comment]
@ajnavarro shall we merge this?

**Pull request merged**
