### PR TITLE
Added from_base64 and to_base64

### LINKED ISSUE #549: Add TO_BASE64, FROM_BASE64
https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_to-base64
https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_from-base64

### PR DESCRIPTION
**Pull request by juanjux**
Another low hanging fruit, adds MySQL's FROM_BASE64 and TO_BASE64 functions.

Fixes #549.

Signed-off-by: Juanjo Alvarez <juanjo@sourced.tech>

### CODE REVIEW

**Comment by erizocosmico** [comment]
Shall we merge this @ajnavarro?

**Comment by juanjux** [comment]
@ajnavarro done!

**Comment by juanjux** [comment]
PR rebased to the new registry and README formats.

**Comment by juanjux** [comment]
PR rebased to the new registry and README formats.

**Comment by juanjux** [comment]
Needs new rebase, working on it.

**Comment by juanjux** [comment]
New rebase done.

**Pull request merged**
