### PR TITLE
sql: implement USE <table> statement

### LINKED ISSUE #411: USE command to change database
Implement use command to change the database in use.

More info: https://github.com/src-d/gitbase/issues/361#issuecomment-427285397

### PR DESCRIPTION
**Pull request by erizocosmico**
Closes #411 

- Implement USE
- Change implementation of UnresolvedDatabase
- Catalog is not thread-safe
- CurrentDatabase is now on the Catalog

### CODE REVIEW

**Comment by ajnavarro** [comment]
@erizocosmico could you add tests for `catalog.CurrentDatabase()`, `catalog.SetCurrentDatabase(...)` and `catalog.AllDatabases()` please?

**Comment by erizocosmico** [comment]
Done, also rebased

**Comment by erizocosmico** [comment]
Rebased again

**Comment by erizocosmico** [comment]
Rebased again

**Pull request merged**
