### PR TITLE
Docs/3rd parties

### LINKED ISSUE #391: Add documentation about compatible clients
Add documentation in a separate file with compatible examples for each language.

For example:

```
## Python
Use pymysql:

import pymysql

conn = pymysql.connect(host='gitbase',
                             user='gitbase',
                             password='',
                             autocommit=False,
                             use_unicode=False)
```

### PR DESCRIPTION
**Pull request by erizocosmico**
Closes #391 

Depends on #396

### CODE REVIEW

**Comment by erizocosmico** [comment]
@kuba-- Rust driver wasn't listed as a client we need to support 😛

**Comment by ajnavarro** [comment]
can you rebase please?

**Comment by erizocosmico** [comment]
Sure

**Comment by erizocosmico** [comment]
Done

**Pull request merged**
