### PR TITLE
sql/plan: make create index sync by default

### PR DESCRIPTION
**Pull request by erizocosmico**
Closes https://github.com/src-d/gitbase/issues/478

Don't merge yet, still need to test about how it handles connection drops.

### CODE REVIEW

**Comment by erizocosmico** [comment]
Noooo, it shouldn't have been merged yet 😭 

> Don't merge yet, still need to test about how it handles connection drops.

**Comment by kuba--** [comment]
Lets use labels (it's easier to notice some bright rectangle than comment).
I've put a label WIP. @erizocosmico - please remove it when you're done.

**Comment by erizocosmico** [comment]
It's already merged, don't worry. I will handle it in another PR.

**Comment by ajnavarro** [comment]
@erizocosmico sorry, I saw the note yesterday, but this morning the only thing I saw was two green checks :(

**Comment by erizocosmico** [comment]
No big deal, after what we discussed yesterday about how cancel should work the PR is more general than for just indexes, so i think it will fit better in another PR.

**Pull request merged**
