### PR TITLE
function: implement JSON_EXTRACT UDF

### LINKED ISSUE #405: Implement JSON_EXTRACT UDF
Implement `JSON_EXTRACT` UDF as defined in MySQL.

See: https://github.com/src-d/gitbase/issues/361#issuecomment-427285397

### PR DESCRIPTION
**Pull request by erizocosmico**
Closes #405

### CODE REVIEW

**Comment by ajnavarro** [comment]
@erizocosmico can you rebase please?

**Comment by ajnavarro** [comment]
@erizocosmico sorry, is broken again... can you rebase pelase?

**Comment by erizocosmico** [comment]
Yup. Damn git and that test

**Comment by erizocosmico** [comment]
Done

**Comment by erizocosmico** [comment]
Fixed

**Pull request merged**
