### PR TITLE
Remove FIRST aggregation expression

### PR DESCRIPTION
**Pull request by mcarmonaa**
`FIRST` is not supported by MySQL

### CODE REVIEW

**Comment by mcarmonaa** [comment]
CI is failing because the `group by` was making use of the `first, I'll fix it

**Comment by ajnavarro** [comment]
@mcarmonaa can you rebase please?

**Comment by mcarmonaa** [comment]
@ajnavarro it's not ready to merge because of #21 , the groupby should be fixed before, I'm on it

**Comment by mcarmonaa** [comment]
#51 fix the problem with the groupby so after merge that PR it should be fine remove the `FIRST` aggregation expression.

**Comment by erizocosmico** [comment]
Rebase needed

**Pull request merged**
