### PR TITLE
Implemented DELETE

### PR DESCRIPTION
**Pull request by Hydrocharged**
Implemented DELETE functionality, along with tests.

### CODE REVIEW

**Comment by Hydrocharged** [comment]
@agarciamontoro Thank you for the typo catches! They have been fixed.

**Comment by erizocosmico** [comment]
Can you PTAL @ajnavarro?

**Comment by ajnavarro** [comment]
@Hydrocharged thanks a lot for your contribution. Could you rebase with master please? Thanks!

**Comment by Hydrocharged** [comment]
> 
> 
> @Hydrocharged thanks a lot for your contribution. Could you rebase with master please? Thanks!

@ajnavarro It looks like https://github.com/src-d/go-mysql-server/pull/825 was already merged in, which included the changes of this PR as well. We don't need to merge this one at all anymore 🎉

**Pull request closed without merging**
