### PR TITLE
sql: implement FIRST and LAST aggregation functions

### LINKED ISSUE #718: Add FIRST/LAST aggregations
* Let's consider adding FIRST/LAST aggregations.
* Present in Spark SQL, not sure if in MySQL.
* In gitbase, these are useful, for example, to get all blobs with _any_ of their associated file names. In our case, running in gitbase-spark-connector without push down may be fine (I'm playing with that now).

### PR DESCRIPTION
**Pull request by erizocosmico**
Closes #718

### CODE REVIEW

**Comment by erizocosmico** [comment]
Tests passing now. Some dependency install failure. Shall we merge this?

**Comment by ajnavarro** [comment]
let's keep this for v0.23.0 gitbase version.

**Comment by ajnavarro** [comment]
@erizocosmico could you rebase please?

**Comment by erizocosmico** [comment]
Rebased

**Pull request merged**
